apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Stable cluster configuration for robot fleet
# Includes robot fleet app and staer-client

resources:
  - ../../collections/stable/robot-fleet
  - ../../collections/stable/staer-client
  # - ../../collections/stable/tailscale     # TODO: Enable when components are ready
